name: Deploy a schema
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm -g install stepzen
      - id: szl
        uses: stepzen-dev/stepzen-login@outputs
        with:
           account: ${{ vars.account }}
           adminkey: ${{ secrets.adminkey }}
      - run: \
         echo domain ${{ steps.szl.outputs.domain }}
         echo account ${{ steps.szl.outputs.account }}
         echo apikey ${{ steps.szl.outputs.apikey }}
